"""
Django settings for vision_code project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL="Accounts.User"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m_jool6a7xb!d5fsh(p-8tr3$2uygn3zmy=ui*i9$oqb#!k7+='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
import os

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
ALLOWED_HOSTS = [ 'localhost', '127.0.0.1','.railway.app']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Accounts',
    'AI_CV_models',
    'Assessments',
    'Courses',
    'Enrollment_Learning',
    'Gamification',
]
INSTALLED_APPS += [
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
     'corsheaders',
]


'''CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]'''
# or for dev:
CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

]

MIDDLEWARE = ["corsheaders.middleware.CorsMiddleware",] + MIDDLEWARE

ROOT_URLCONF = 'vision_code.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vision_code.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'VISION_CODE',        # Database name you just created
        'USER': 'postgres',          # Username
        'PASSWORD': 'admin123',      # Password we reset
        'HOST': 'localhost',         # Host
        'PORT': '5432',              # Port
    }
    
}
'''
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "postgres",  
        "USER": "postgres.oktqnovgjwwzujnqlmoj",  
        "PASSWORD": "5g&kjZ+8D4NYtZ3",
        "HOST": "aws-1-ap-south-1.pooler.supabase.com",  
        "PORT": "5432",
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),

}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

SIMPLE_JWT = {
    "TOKEN_OBTAIN_SERIALIZER": "Accounts.token_serializers.CustomTokenObtainPairSerializer",
    # 🔐 ACCESS TOKEN (used in every API request)
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=6),

    # 🔁 REFRESH TOKEN (used to get new access token)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    # Rotate refresh tokens (recommended)
    "ROTATE_REFRESH_TOKENS": True,

    # Blacklist old refresh tokens (recommended)
    "BLACKLIST_AFTER_ROTATION": True,

    # Security settings
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),

    # Optional but good
    "UPDATE_LAST_LOGIN": True,
}
