# Generated by Django 6.0 on 2025-12-10 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('starter_code', models.JSONField(default=dict)),
                ('test_cases', models.JSONField(default=list)),
                ('hints', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('time_limit_minutes', models.IntegerField()),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_problem', to='Courses.contentitem')),
            ],
            options={
                'db_table': 'coding_problems',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('programming_language', models.CharField(max_length=50)),
                ('execution_results', models.JSONField(default=dict)),
                ('passed_all_tests', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('plagiarism_report', models.JSONField(default=dict)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Assessments.codingproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_index', models.IntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('output', models.TextField()),
                ('execution_time', models.FloatField(default=0.0)),
                ('error_message', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_results', to='Assessments.submission')),
            ],
            options={
                'db_table': 'test_case_results',
            },
        ),
    ]
