# Generated by Django 6.0 on 2026-02-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Assessments", "0001_initial"),
        (
            "Courses",
            "0002_alter_contentitem_options_remove_contentitem_content_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="Courses.codingproblem",
            ),
        ),
        migrations.DeleteModel(
            name="CodingProblem",
        ),
    ]
