# Generated by Django 6.0 on 2025-12-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('adaptive_learning', 'Adaptive Learning'), ('nlp', 'NLP'), ('computer_vision', 'Computer Vision'), ('recommendation', 'Recommendation')], max_length=30)),
                ('version', models.CharField(max_length=50)),
                ('model_parameters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Ai_models',
            },
        ),
        migrations.CreateModel(
            name='CVSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('attention_metrics', models.JSONField(default=dict)),
                ('emotion_data', models.JSONField(default=dict)),
                ('engagement_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'cv_sessions',
            },
        ),
    ]
