# Generated by Django 6.0 on 2025-12-05 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI_CV_models', '0001_initial'),
        ('Courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsession',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_sessions', to='Courses.contentitem'),
        ),
        migrations.AddField(
            model_name='cvsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
