# Generated by Django 6.0 on 2026-02-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentitem",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="contentitem",
            name="content",
        ),
        migrations.RemoveField(
            model_name="contentitem",
            name="metadata",
        ),
        migrations.AddField(
            model_name="contentitem",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contentitem",
            name="order",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("article", "Article"),
                    ("quiz", "Quiz"),
                    ("coding_problem", "Coding Problem"),
                    ("assignment", "Assignment"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="estimated_duration_minutes",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("summary", models.TextField(blank=True)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article",
                        to="Courses.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "articles",
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructions", models.TextField()),
                ("max_score", models.PositiveIntegerField()),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment",
                        to="Courses.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "assignments",
            },
        ),
        migrations.CreateModel(
            name="CodingProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_statement", models.TextField()),
                ("constraints", models.TextField(blank=True)),
                ("starter_code", models.JSONField(default=dict)),
                ("time_limit_seconds", models.PositiveIntegerField(default=1)),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_problem",
                        to="Courses.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "coding_problems",
            },
        ),
        migrations.CreateModel(
            name="CodingTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField()),
                ("expected_output", models.TextField()),
                ("is_hidden", models.BooleanField(default=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="Courses.codingproblem",
                    ),
                ),
            ],
            options={
                "db_table": "coding_test_cases",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_marks", models.PositiveIntegerField()),
                ("passing_marks", models.PositiveIntegerField()),
                (
                    "content_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="Courses.contentitem",
                    ),
                ),
            ],
            options={
                "db_table": "quizzes",
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("order", models.PositiveIntegerField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="Courses.quiz",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="Courses.quizquestion",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_options",
            },
        ),
    ]
