# Generated by Django 6.0 on 2026-04-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Courses",
            "0002_alter_contentitem_options_remove_contentitem_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
